os:
    - linux 
    - osx

language: 
    - cpp

before_install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get update --fix-missing && sudo apt-get install -y libsndfile1-dev && sudo apt-get install -y libpulse-dev && sudo apt-get install -y libasound2-dev; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then echo "before_install - osx"; fi
    
script: 
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cd src/ && make linux-pulse; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then cd src/ && make osx; fi
    
    - sudo mv ./chuck /usr/local/bin/
    - cd test/
    - python test.py
    
after_success:
    - echo "Success!"

after_failure:
    - echo "Something went wrong..."