
CK_SRC_PATH=../../src/
CHUGIN_PATH=/usr/lib/chuck

CHUGINS=path
CHUGS=$(addsuffix .chug,$(CHUGINS))

all: $(CHUGS)

$(CHUGS): %.chug: %.cpp $(CK_SRC_PATH)/chuck_dl.h
	gcc -g -m32 -Wl,-undefined,dynamic_lookup -rdynamic -bundle -o $@ $< \
    -D__MACOSX_CORE__ -lstdc++ -I$(CK_SRC_PATH)

install: $(CHUGS)
	mkdir -p $(CHUGIN_PATH)
	cp $^ $(CHUGIN_PATH)

